### ISSUE TITLE
formulae require at least 1 url

### ISSUE THREAD

**Issue by hazcod** [caffix/homebrew-amass#2]
Hi, trying to update to latest amass on apple silicon.

```
% brew update
Already up-to-date.
% brew info amass
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:253:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:206:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:366:in `factory'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:87:in `load_formula_or_cask'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:74:in `block in to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:73:in `map'
/opt/homebrew/Library/Homebrew/cli/named_args.rb:73:in `to_formulae_and_casks_and_unavailable'
/opt/homebrew/Library/Homebrew/cmd/info.rb:139:in `print_info'
/opt/homebrew/Library/Homebrew/cmd/info.rb:102:in `info'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
% brew upgrade ; brew cleanup
Error: formulae require at least a URL
/opt/homebrew/Library/Homebrew/formula.rb:253:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:206:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:153:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:305:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:366:in `factory'
/opt/homebrew/Library/Homebrew/formulary.rb:413:in `from_keg'
/opt/homebrew/Library/Homebrew/formulary.rb:386:in `from_rack'
/opt/homebrew/Library/Homebrew/cleanup.rb:85:in `stale_formula?'
/opt/homebrew/Library/Homebrew/cleanup.rb:58:in `stale?'
/opt/homebrew/Library/Homebrew/cleanup.rb:321:in `block in cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:304:in `each'
/opt/homebrew/Library/Homebrew/cleanup.rb:304:in `cleanup_cache'
/opt/homebrew/Library/Homebrew/cleanup.rb:192:in `clean!'
/opt/homebrew/Library/Homebrew/cmd/cleanup.rb:58:in `cleanup'
/opt/homebrew/Library/Homebrew/brew.rb:122:in `<main>'
```

**Comment by caffix** [comment]
The new casks should fix this issue
